### create reports

POST http://localhost:3000/reports
content-type: application/json
 
  {
   "make": "toyota",
   "model": "corolla",
   "year": 1982,
   "mileage": 100000,
   "lng": 45,
   "lat": 45,
   "price": 20000
  }



### Change approval status

PATCH  http://localhost:3000/reports/6344769999197eb78506be66
content-type: application/json

{
  "approved": true
}

### get estimate for existing vehicle
GET https://carsify-gamma.vercel.app/reports?make=toyota&model=mustang&lng=45&lat=45&mileage=2000&year=1982