POST http://localhost:3000/auth/signup
content-type: application/json
 
  {
    "email": "chisom@gmail.com",
    "password": "12345"
  }

### signin

POST http://localhost:3000/auth/signin
content-type: application/json
 
  {
    "email": "chisom@gmail.com",
    "password": "12345"
  }
 


### find users

GET http://localhost:3000/auth?email=chisom@gmail.com

### get user by ID

GET http://localhost:3000/auth/633d5a8e2fca515ff5bb2876


### delete user

DELETE http://localhost:3000/auth/633d6b35cf32cb209c0e30a4


### Update User

PATCH http://localhost:3000/auth/633d5a8e2fca515ff5bb2876
content-type: application/json
 
  {
    "email": "jerry1@gmail.com",
    "password": "1234"
  }

### cookies - color

Get http://localhost:3000/auth/colors/red

###

Get http://localhost:3000/auth/colors