POST https://carsify-gamma.vercel.app/auth/signup
content-type: application/json
 
  {
    "email": "jerry@gmail.com",
    "password": "1234"
  }

### signin

POST https://carsify-gamma.vercel.app/auth/signin
content-type: application/json
 
  {
    "email": "jerry@gmail.com",
    "password": "1234"
  }
 
### who am I

GET https://carsify-gamma.vercel.app/auth/whoami

### signout
Post https://carsify-gamma.vercel.app/auth/signout

### find users

GET https://carsify-gamma.vercel.app/auth?email=jerry@gmail.com

### get user by ID

GET https://carsify-gamma.vercel.app/auth/633e94ee8290d64be7448304


### delete user

DELETE https://carsify-gamma.vercel.app/auth/633d6b35cf32cb209c0e30a4


### Update User

PATCH https://carsify-gamma.vercel.app/auth/63447b246adeb4277faa08da
content-type: application/json
 
  {
    "email": "jerry@gmail.com"
  }

### change user password

POST https://carsify-gamma.vercel.app/auth/changepassword
content-type: application/json

{
  "email": "jerry@gmail.com",
   "oldPassword": "12345",
  "newPassword": "1234"
  }






